global:
  scrape_interval: 10s
  scrape_timeout: 5s
  query_log_file: /prometheus/query.log

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:9090'
          - 'localhost:7000'
          - 'localhost:7001'
          - 'localhost:7002'
          - 'localhost:7003'
          - 'localhost:7004'
          - 'localhost:7005'