{
 "title": "We Talk Together",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Produced Items",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(producer_request_bucket[5m])) by (le))",
     "legendFormat": "Average Seconds"
    }
   ]
  },
  {
   "title": "Produced Items Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(producer_request_count) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Consumers Concurrent Calls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consumer_concurrent_call", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consumer_concurrent_call", "legendFormat": "{{app}}" }
   ]
  }
 ]
}