filebeat.inputs:
- type: filestream
  id: "q"
  enabled: true
  paths:
    - /home/wagner/.pm2/logs/*.log
logging.level: info
setup.kibana:
  host: "http://0.0.0.0:5601"
output.elasticsearch:
  hosts: ["http://0.0.0.0:9200"]
  username: "beaty"
  password: "pass123"